name 'hbai-microsoft_sysinternals'
version '0.0.1'
author 'Haishi Bai'
license 'Apache License, Version 2.0'
summary 'This module installs Process Explorer as the Windows Task Manager'
description 'This module installs Process Explorer as the Windows Task Manager.'
dependency 'joshcooper/powershell'
dependency 'puppetlabs/registry'
